name: 'Test AWS'
description: 'Test AWS'
inputs:
  environment:
    description: 'environment - used to switch'
    required: true
  aws_access_key:  # id of input
    description: 'aws_access_key'
    required: true
  aws_secret_access_key:
    description: 'aws_secret_access_key'
    required: true
  patchVersion:
    description: "version to patch"
    required: true
  task_definition_name:
    description: "name of the task definition"
    required: true
  

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws_access_key: ${{ inputs.aws_access_key }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Log the new image ID that will go into the Amazon ECS task definition
      shell: bash
      run: |
        echo "Patch version: ${{ inputs.patchVersion }}"
        echo "into env ${{ inputs.environment }}
    - name: Download task definition - and excise env vars
      id: task-definition-download
      shell: bash
      run: |
        taskDefinition=${{ inputs.task_definition_name }}
        aws ecs describe-task-definition --task-definition ${taskDefinition} --query taskDefinition > TaskDefinition.json
        # then remove env vars
        aws ecs describe-task-definition --task-definition ${taskDefinition} --query taskDefinition | jq 'del(.containerDefinitions[0].environment)' | jq 'del(.containerDefinitions[1].environment)' > tempTaskDefinition.json


# name: 'Hello World'
# description: 'Greet someone'
# inputs:
#   who-to-greet:  # id of input
#     description: 'Who to greet'
#     required: true
#     default: 'World'
# outputs:
#   random-number:
#     description: "Random number"
#     value: ${{ steps.random-number-generator.outputs.random-number }}
# runs:
#   using: "composite"
#   steps:
#     - run: echo Hello ${{ inputs.who-to-greet }}.
#       shell: bash
#     - id: random-number-generator
#       run: echo "::set-output name=random-number::$(echo $RANDOM)"
#       shell: bash
#     - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
#       shell: bash          
#     - run: goodbye.sh
#       shell: bash
